CREATE TABLE IF NOT EXISTS WeaponType (
    name VARCHAR(16) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Weapon (
    identifier INTEGER PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    damage_min INTEGER,
    damage_max INTEGER,
    type VARCHAR(16) NOT NULL,
    critical_rate REAL,
    speed REAL,
    FOREIGN KEY(type) REFERENCES WeaponType(name)
);

INSERT INTO WeaponType VALUES ("ONE_HAND_SWORD");
INSERT INTO WeaponType VALUES ("TWO_HANDS_SWORD");
INSERT INTO WeaponType VALUES ("ONE_HAND_AXE");
INSERT INTO WeaponType VALUES ("TWO_HANDS_AXE");
INSERT INTO WeaponType VALUES ("ONE_HAND_MACE");
INSERT INTO WeaponType VALUES ("TWO_HANDS_MACE");
INSERT INTO WeaponType VALUES ("STAFF");
INSERT INTO WeaponType VALUES ("BOW");
INSERT INTO WeaponType VALUES ("CROSSBOW");

